# Generated by Django 5.2.7 on 2025-11-26 12:48

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название подразделения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TickerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Цитата для бегущей строки',
                'verbose_name_plural': 'Цитаты для бегущей строки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news_site.category', verbose_name='Родительская категория')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news_site.section', verbose_name='Раздел')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'title'],
                'unique_together': {('section', 'slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news_site.category', verbose_name='Категория')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news_site.section', verbose_name='Раздел')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news_files/', verbose_name='Файл')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news_site.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Файл новости',
                'verbose_name_plural': 'Файлы новостей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время скачивания')),
                ('news_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_site.newsfile', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Статистика скачиваний',
                'verbose_name_plural': 'Статистика скачиваний',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.subdivision', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='ViewStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(max_length=500, verbose_name='Путь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.category', verbose_name='Категория')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.news', verbose_name='Новость')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Статистика просмотров',
                'verbose_name_plural': 'Статистика просмотров',
                'ordering': ['-created_at'],
            },
        ),
    ]
